// the gallery's shader list -- the data layer. each entry points at a .frag asset
// (fetched + compiled at runtime) and carries a coolness 0..100 that drives tile
// size today and is the field people will vote on later. add a shader = drop its
// .frag in assets/ and add a line here. generated from assets/ but freely editable.

import type { ShaderDef } from "./shader.ts"

export const MANIFEST: ShaderDef[] = [
  { frag_url: "assets/4thdimension.frag", coolness: 93 },
  { frag_url: "assets/E.frag", coolness: 94 },
  { frag_url: "assets/E2.frag", coolness: 26 },
  { frag_url: "assets/E3.frag", coolness: 27 },
  { frag_url: "assets/E3_2.frag", coolness: 53 },
  { frag_url: "assets/E3_3.frag", coolness: 54 },
  { frag_url: "assets/E3_4.frag", coolness: 55 },
  { frag_url: "assets/E3_5.frag", coolness: 56 },
  { frag_url: "assets/E3_6.frag", coolness: 57 },
  { frag_url: "assets/E3_7.frag", coolness: 58 },
  { frag_url: "assets/E3_8.frag", coolness: 59 },
  { frag_url: "assets/E3_9.frag", coolness: 60 },
  { frag_url: "assets/E4.frag", coolness: 28 },
  { frag_url: "assets/E5.frag", coolness: 29 },
  { frag_url: "assets/E6.frag", coolness: 30 },
  { frag_url: "assets/E7.frag", coolness: 31 },
  { frag_url: "assets/amongus-coloring.frag", coolness: 83 },
  { frag_url: "assets/amongus-tiling-1-old.frag", coolness: 38 },
  { frag_url: "assets/amongusfail.frag", coolness: 83 },
  { frag_url: "assets/artdeco.frag", coolness: 72 },
  { frag_url: "assets/beach-house.frag", coolness: 36 },
  { frag_url: "assets/beast.frag", coolness: 73 },
  { frag_url: "assets/beast2.frag", coolness: 58 },
  { frag_url: "assets/beast3.frag", coolness: 59 },
  { frag_url: "assets/beast4.frag", coolness: 60 },
  { frag_url: "assets/beast5.frag", coolness: 61 },
  { frag_url: "assets/blocks.frag", coolness: 63 },
  { frag_url: "assets/checkerboard.frag", coolness: 40 },
  { frag_url: "assets/cheese.frag", coolness: 72 },
  { frag_url: "assets/chicago.frag", coolness: 36 },
  { frag_url: "assets/dateline.frag", coolness: 45 },
  { frag_url: "assets/dna.frag", coolness: 78 },
  { frag_url: "assets/everywhere.frag", coolness: 59 },
  { frag_url: "assets/farlands.frag", coolness: 87 },
  { frag_url: "assets/fence.frag", coolness: 83 },
  { frag_url: "assets/glalie.frag", coolness: 33 },
  { frag_url: "assets/glalie2.frag", coolness: 74 },
  { frag_url: "assets/glalie3_selector.frag", coolness: 50 },
  { frag_url: "assets/glalie4_diva_intro.frag", coolness: 75 },
  { frag_url: "assets/hallway.frag", coolness: 85 },
  { frag_url: "assets/hallway_2.frag", coolness: 90 },
  { frag_url: "assets/hallway_3.frag", coolness: 91 },
  { frag_url: "assets/hatch.frag", coolness: 60 },
  { frag_url: "assets/hex.frag", coolness: 45 },
  { frag_url: "assets/hexsdf.frag", coolness: 76 },
  { frag_url: "assets/insect-christmas.frag", coolness: 49 },
  { frag_url: "assets/interlinked.frag", coolness: 35 },
  { frag_url: "assets/kazakhfractal.frag", coolness: 79 },
  { frag_url: "assets/linedance.frag", coolness: 94 },
  { frag_url: "assets/linedance2.frag", coolness: 65 },
  { frag_url: "assets/lines.frag", coolness: 95 },
  { frag_url: "assets/louiebag.frag", coolness: 66 },
  { frag_url: "assets/mangle.frag", coolness: 56 },
  { frag_url: "assets/noise.frag", coolness: 28 },
  { frag_url: "assets/pentagon.frag", coolness: 84 },
  { frag_url: "assets/pixel.frag", coolness: 80 },
  { frag_url: "assets/plot.frag", coolness: 88 },
  { frag_url: "assets/plot2.frag", coolness: 29 },
  { frag_url: "assets/plot3.frag", coolness: 30 },
  { frag_url: "assets/pokeball.frag", coolness: 74 },
  { frag_url: "assets/purple.frag", coolness: 51 },
  { frag_url: "assets/purple2.frag", coolness: 80 },
  { frag_url: "assets/quasar.frag", coolness: 67 },
  { frag_url: "assets/quasar2.frag", coolness: 73 },
  { frag_url: "assets/rhombus.frag", coolness: 64 },
  { frag_url: "assets/shadertoy.frag", coolness: 82 },
  { frag_url: "assets/shades.frag", coolness: 87 },
  { frag_url: "assets/sticks.frag", coolness: 82 },
  { frag_url: "assets/tiger.frag", coolness: 68 },
  { frag_url: "assets/timewarp.frag", coolness: 37 },
  { frag_url: "assets/toon.frag", coolness: 91 },
  { frag_url: "assets/triangle.frag", coolness: 66 },
  { frag_url: "assets/tunnel.frag", coolness: 44 },
  { frag_url: "assets/tunnel2.frag", coolness: 25 },
  { frag_url: "assets/tunnel_small.frag", coolness: 70 },
  { frag_url: "assets/wave.frag", coolness: 69 },
  { frag_url: "assets/wave2.frag", coolness: 87 },
  { frag_url: "assets/waves.frag", coolness: 81 },
  { frag_url: "assets/x.frag", coolness: 74 },
]
