services:
  cwab:
    container_name: cwab
    build: .
    image: cwab:latest
    restart: unless-stopped
    environment:
      - CWAB_DB=/data/cwab.db
    volumes:
      - cwab-data:/data
    ports:
      # backend uses port 3000, but docker will actually expose 3333
      # ngl this was a quick and easy fix since i needed port 3000 for
      # something more important
      - "3333:3000"
    networks:
      - cwabnetwork

  tunnel:
    container_name: cwab-cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      - cwabnetwork

networks:
  cwabnetwork:
    driver: bridge

volumes:
  cwab-data:
